### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by maximilianmeier** [js-data/js-data-hal#1]
I wanted to install the bower component with:
"bower install --save js-data-hal"
but it can't find the component:
"ENOTFOUND Package js-data-hal not found"

I also tried to install it with:
"bower install --save https://github.com/js-data-js/data-hal.git"
this worked but the depedency version of this repo is 0.4.x.
But the most current version is 2.9.0

Help very appreciated :smile: 

To extend my question a bit:

Do you know if I can use this adapter in combination with js-data-angular?

**Comment by jmdobry** [comment]
Sorry, this adapter hasn't actually been fully implemented, and no `js-data-hal` package has been published yet. This repo was just created with some boilerplate, back when someone had expressed interest in working on it...but they never did. The official adapters are the ones mentioned in the docs.
